server:
  servlet:
    context-path:
  port: 8081

spring.datasource.url: jdbc:postgresql://db:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: root
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

spring.datasource.initialization-mode: always
spring.datasource.schema: classpath:schema.sql
spring.datasource.data: classpath:data.sql
