version: '3'
services:
  db:
    container_name: 'postgres'
    networks:
      - network_roman
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  dbGUI:
    container_name: 'pgadmin'
    networks:
      - network_roman
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kenny@example.com"
      PGADMIN_DEFAULT_PASSWORD: "kenny"
    ports:
      - "16543:80"
    depends_on:
      - db
  caesar:
    container_name: 'caesar'
    networks:
      - network_roman
    build: ./caesar
    image: caesar:latest
    entrypoint: ["java","-jar","/app.jar"]
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
  postman:
    container_name: 'postman'
    networks:
      - network_roman
      - network_battlefront
    build: ./postman
    image: postman:latest
    entrypoint: ["java","-jar","/app.jar"]
    restart: always
    ports:
      - "8082:8081"
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - network_battlefront
    container_name: postman_redis
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  pompeii:
    container_name: 'pompeii'
    networks:
      - network_battlefront
    build: ./pompeii
    image: pompeii:latest
    entrypoint: ["java","-jar","/app.jar"]
    restart: always
    ports:
      - "8083:8081"
    depends_on:
      - redis
networks:
  network_roman:
    driver: bridge
  network_battlefront:
    driver: bridge
